// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzdo6GDLsu0OjNvhan4U-RDK378xqzl-E',
    appId: '1:336039829559:web:f3d5fdbb65571f179adfb2',
    messagingSenderId: '336039829559',
    projectId: 'studentswipe-549e9',
    authDomain: 'studentswipe-549e9.firebaseapp.com',
    storageBucket: 'studentswipe-549e9.firebasestorage.app',
    measurementId: 'G-1C7WYE9BPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk4KhiHDXgXLtGGf9lEepmy8QFUT_Gl48',
    appId: '1:336039829559:android:98661ec4a0e441ea9adfb2',
    messagingSenderId: '336039829559',
    projectId: 'studentswipe-549e9',
    storageBucket: 'studentswipe-549e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlg0H8_FY7SKiFNgDnzyvUjn_QutdNyYE',
    appId: '1:336039829559:ios:032938f053e2aad39adfb2',
    messagingSenderId: '336039829559',
    projectId: 'studentswipe-549e9',
    storageBucket: 'studentswipe-549e9.firebasestorage.app',
    iosClientId: '336039829559-lniv84galv04uhk28c1qvneipphu7a1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentSwipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlg0H8_FY7SKiFNgDnzyvUjn_QutdNyYE',
    appId: '1:336039829559:ios:032938f053e2aad39adfb2',
    messagingSenderId: '336039829559',
    projectId: 'studentswipe-549e9',
    storageBucket: 'studentswipe-549e9.firebasestorage.app',
    iosClientId: '336039829559-lniv84galv04uhk28c1qvneipphu7a1i.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentSwipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzdo6GDLsu0OjNvhan4U-RDK378xqzl-E',
    appId: '1:336039829559:web:d57860cee4146b679adfb2',
    messagingSenderId: '336039829559',
    projectId: 'studentswipe-549e9',
    authDomain: 'studentswipe-549e9.firebaseapp.com',
    storageBucket: 'studentswipe-549e9.firebasestorage.app',
    measurementId: 'G-GWZ621X047',
  );
}
